### ISSUE TITLE
Cleanup when loosing peer

### ISSUE THREAD

**Issue by ghost** [gatzka/cjet#29]
All states and methods of a lost peer are to be removed. This seems not to happen in the moment.
I start a process that successfully creates some states. When killing this process, states belonging to it are not being removed.

**Comment by gatzka** [comment]
A small test does not prove it. I used the cpp jet client test "testState", which adds a state. I killed the process, even with kill -9 and restarted "testState". The state is added successfully. Any more information  on this issue?

**Comment by ghost** [comment]
I'll try to reproduce the error...

**Comment by ghost** [comment]
well, I need to apologize. Everything seems right.
