### ISSUE TITLE
fetch has to deliver matching states and methods

### ISSUE THREAD

**Issue by ghost** [gatzka/cjet#9]
cjet delivers matching states only

**Comment by gatzka** [comment]
O.k., have you clarified this with Gerd? That's how the fetch is supposed to work? What about luajet/nodejet?

**Comment by ghost** [comment]
Yes, I Talkes with Gerd about the Issing. This is not an urgent problem. Have some nice days!

**Comment by gatzka** [comment]
O.k., I assume it a fetch method message is exactly the same like a fetched state message but without a value, correct?

In addition, is it allowed to have a state and a method with the same name (key)?

**Comment by ghost** [comment]
Yes, the fetch notification of a method does not contain a value. Hence event may be "add" or "remove" only.

As of my knowledge a path has to be unique regardless of the type of thing it does describe.

**Comment by ghost** [comment]
I've been looking around the fetch mechanism. Right now there is are lists of states matching a fetch. There are two alternatives now: Creating a second list with matching methods or adding and methods to the same list. I suggest adding states and methods to one list and setting the notifying function pointer to the appropriate function.

**Comment by gatzka** [comment]
Resolved

**Comment by ghost** [comment]
this is really nice, all my jet peer tests do succeed now with cjet as jet daemon!
